export const FETCH_PRODUCT_START ='FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL='FETCH_PRODUCT_FAIL'


export const FETCH_CART_SUCCESS='FETCH_CART_SUCCESS'
export const FETCH_CART_FAIL='FETCH_CART_FAIL'
export const FETCH_CART_START='FETCH_CART_START'

export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_FROM_CART='REMOVE_FROM_CART'
export const EMPTY_CART='EMPTY_CART'
export const UPDATE_CART='UPDATE_CART'
export const TO_STORE_CART_START='TO_STORE_CART_START'
export const TO_STORE_CART_FAIL='TO_STORE_CART_FAIL'

export const SUBTRACT_ON_CART='SUBTRACT_ON_CART'
export const ADD_ON_CART='ADD_ON_CART'

export const AUTH_START='AUTH_START'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAIL='AUTH_FAIL'
export const AUTH_ADDRESS__START='AUTH_ADDRESS__START'
export const AUTH_ADDRESS_SUCCESS='AUTH_ADDRESS_SUCCESS'
export const AUTH_ADDRESS_FAIL='AUTH_ADDRESS_FAIL'
export const AUTH_CLEAR_ERROR='AUTH_CLEAR_ERROR'
export const AUTH_SUBSCRIBE='AUTH_SUBSCRIBE'
export const AUTH_SET_PATH='AUTH_SET_PATH'
export const AUTH_LOGOUT='AUTH_LOGOUT'
export const AUTH_TRIGGER='AUTH_TRIGGER'

export const ORDER_START='ORDER_START'
export const ORDER_SUCCESS='ORDER_SUCCESS'
export const ORDER_FAIL='ORDER_FAIL'
export const ORDER_PATH='ORDER_PATH'
export const EMPTY_ORDER='EMPTY_ORDER'

export const CONFIRM_ORDER_START='CONFIRM_ORDER_START'
export const CONFIRM_ORDER_SUCCESS='CONFIRM_ORDER_SUCCESS'
export const CONFIRM_ORDER_FAIL='CONFIRM_ORDER_FAIL'
export const CONFIRM_ORDER_PATH='CONFIRM_ORDER_PATH'

export const ORDER_LIST_START='ORDER_LIST_START'
export const ORDER_LIST_SUCCESS='ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL='ORDER_LIST_FAIL'
export const ORDER_DETAIL_SUCCESS='ORDER_DETAIL_SUCCESS'







