export { default as  authReducer} from './auth'
export{ default as cartReducer} from './cart'
export{ default as orderReducer} from './order'
export{ default as  productReducer} from './product'
export{ default as  orderListReducer} from './orderList'